<script lang="ts">
  export let title: string;
  export let elements: Array<{
    type: string;
    text?: string; // For subtitle
    content?: string; // For text (HTML)
    // Properties for other types like list, image, video will be added later
  }> = [];
</script>

<div class="content-template-slide">
  <h2>{title}</h2>
  {#each elements as element}
    {#if element.type === 'subtitle'}
      <h3>{element.text}</h3>
    {:else if element.type === 'text'}
      {@html element.content}
    <!--
      Placeholder for other element types:
      {:else if element.type === 'list'}
        <p>[List element placeholder]</p>
      {:else if element.type === 'image'}
        <p>[Image element placeholder]</p>
      {:else if element.type === 'video'}
        <p>[Video element placeholder]</p>
      {:else}
        <p style="color: red;">Unknown element type: {element.type}</p>
      -->
    {/if}
  {/each}
</div>

<style>
  .content-template-slide {
    padding: 2rem;
    text-align: left;
  }

  h2 {
    font-size: 2.5em;
    margin-bottom: 0.75em;
  }

  h3 { /* Style for subtitles */
    font-size: 1.75em;
    margin-top: 1em;
    margin-bottom: 0.5em;
    color: #333;
  }

  /* Styling for paragraphs generated by {@html element.content} */
  :global(.content-template-slide p) {
    font-size: 1em;
    line-height: 1.6;
    margin-bottom: 1em;
  }

  /* Styling for strong tag within paragraphs */
  :global(.content-template-slide p strong) {
    font-weight: bold;
  }
</style>
